package MAIN;
import java.sql.Connection;
import java.sql.ResultSet;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
public class Variables {
	public static String cadena_html = ""; 
	public static String cadena_html_descripcion = null;
	public static Boolean valida_caso = false;
	public static String hora_inicio = "";
	public static String hora_final = "";
	public static String tiempo_ejecu = "";
	public static WebDriver driver;
	public static WebElement element;
	public static Connection Cnn = null;
	public static Connection CnnOracle = null;
	public static boolean bln_cerrar_browser = true;
	public static ResultSet Rst_Indice = null;
	public static ResultSet Rst_Objetos = null;
	public static ResultSet Rst_Datos = null;
	public static ResultSet Rst_Pasos_Read = null;
	public static ResultSet Rst_Datos_Read = null;
	public static ResultSet Rst_descripcion_caso = null;
	public static Boolean blnpendiente= false;
	public static String P_Nombre_Maquina =  "";
	public static String P_Entrada_Sistema =  "";
	public static ResultSet Rst_Escenarios_Pendientes = null;
	public static String dtFechaInicio= null;
	public static String dtFechaFinal= null;
	public static String str_escenario;
	public static String P_Tipo_Paso=null;
	public static String P_Paso=null;
	public static String P_Object=null;
	public static String P_Parametro_Adicional=null;
	public static String P_Automatico=null;
	public static String O_Object_Name=null;
	public static String O_Object_Ident=null;
	public static String O_Tipo_Object_Ident=null;
	public static String D_Dato=null;
	public static String file;
	public static String web;
	public static String S_Version=null;
	public static String S_Corrida=null;
	public static String S_Arquitecto_QA=null;
	public static ResultSet Rst_Leer_Cadena_Html_Final = null;
	public static String str_Leer_Cadena_Html_Final=null;
	public static String ruta;
	public static ResultSet Rst_ScreenShoot_PNG = null;
	public static String str_ScreenShoot_PNG=null;
	public static String dtFechaInicioCaso= null;
	public static Long total_seg=null;
	public static ResultSet Rst_Total = null;
	public static ResultSet Rst_OK = null;
	public static ResultSet Rst_ERROR = null;
	public static Boolean bln_Captura_Total=false;
	public static Boolean bln_Solo_Evidencia=false;
	public static String S_Casos_Ejecutar = null;
	public static String casos_ejecutar  = "";
	public static String D_ID_CASO="";
	public static String P_ID_PASO="";
	public static Boolean bln_demonio_escenario=false;
	public static Integer Str_Tipo_Ejecucion;
}
